---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    azkaban_db: azkaban
    azkaban_version: 3.50.2
    azkaban_source_dir: /opt/azkaban/
  pre_tasks:
   - name: 'install python 2 and 3'
     raw: apt-get -y update && apt-get install -y python python3
  tasks:
   - name: update apt cache
     apt: update_cache=yes

   - name: Install add-apt-repostory
     apt: name=software-properties-common state=latest

   - name: Add Oracle Java Repository
     apt_repository: repo='ppa:webupd8team/java'

   - name: Accept Java 8 License
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

   - name: Install packages
     apt: pkg={{ item }} state=latest
     with_items:
       - mysql-server
       - mysql-client
       - python-mysqldb
       - vim
       - oracle-java8-installer
       - ca-certificates
       - oracle-java8-set-default

   - name: Ensure azkaban DB is present
     mysql_db: name={{ azkaban_db }} state=present

   - name: Ensure azkaban DB user is present with correct privileges
     mysql_user: name=azkaban password=azkaban
                 priv={{ azkaban_db }}.*:SELECT,INSERT,UPDATE,DELETE,INDEX,DROP,CREATE,REFERENCES,GRANT
                 state=present

   - name: Update Mysql config
     copy: src=data/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
           owner=root group=root
           mode=0644

   - name: Restart service mysql, in all cases
     service:
       name: mysql
       state: restarted
       enabled: true

   - name: Create main folder for Azkaban 3
     file: 
       path: "{{ azkaban_source_dir }}"
       state: directory
       mode: 0755
       owner: vagrant
       group: vagrant

   - name: Get Azkaban 3 Source from Git
     git:
       repo: https://github.com/azkaban/azkaban.git
       dest: "{{ azkaban_source_dir }}"
       force: yes
       version: "{{ azkaban_version }}"

   - name: Change permisions for Azkaban 3 folder
     file: 
       dest: "{{ azkaban_source_dir }}"
       owner: vagrant
       group: vagrant
       mode: 0755
       recurse: yes

   - name: Initial Build of Azkaban 3 (./gradlew build installDist)
     shell: ./gradlew build installDist
     args:
       chdir: "{{ azkaban_source_dir }}"
       executable: /bin/bash
     become: false 

   - name: Create extlib folder for Azkaban 3
     file:
       path: /opt/azkaban/azkaban-solo-server/build/install/azkaban-solo-server/extlib/
       state: directory
       mode: 0755
       owner: vagrant
       group: vagrant

   - name: Add extlib forr mysql
     copy: src=data/mysql-connector-java-8.0.12.jar dest=/opt/azkaban/azkaban-solo-server/build/install/azkaban-solo-server/extlib/mysql-connector-java-8.0.12.jar
           owner=vagrant group=vagrant
           mode=0755

   - name: Replace config to azkaban use mysql
     copy: src=data/azkaban.properties dest=/opt/azkaban/azkaban-solo-server/build/install/azkaban-solo-server/conf/azkaban.properties
           owner=vagrant group=vagrant
           mode=0755

   - name: Add azkaban as a service
     copy: src=data/azkaban-solo-server.service dest=/etc/systemd/system/azkaban-solo-server.service
           owner=root group=root
           mode=0755

   - name: Configure azkaban service
     systemd:
       state: started
       daemon_reload: yes
       name: azkaban-solo-server
       enabled: true
